branches:
  only:
    - master

language: common-lisp
sudo: required

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    #- LISP=sbcl32
    - LISP=ccl
    #- LISP=ccl32
    #- LISP=clisp
    #- LISP=clisp32
    #- LISP=cmucl
    #- LISP=ecl

install:
  # Install cl-travis
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  # Install dependencies
  - git clone --depth=1 git://github.com/trivial-features/trivial-features.git ~/lisp/trivial-features
  - git clone https://gitlab.common-lisp.net/alexandria/alexandria.git ~/lisp/alexandria

script:
  - cl -l lift
       -e ';;(ql:quickload :cffi-tests)
           (lift:run-tests :suite 'root)'
